### ISSUE TITLE
test_RAG_ted.py

### ISSUE THREAD

**Issue by 223d** [zyhbili/LivelySpeaker#1]
你好，
运行自己训练结果来进行测试，python scripts/test_RAG_ted.py --model_path ckpts/TED/model000586891.pt，会出现以下问题：
test len 26245
train len 200038
Loading checkpoints from [ckpts/TED/opt000586891.pt]...
missing_keys ['backbone.mlps.0.block1.0.alpha', 'backbone.mlps.0.block1.0.beta', 'backbone.mlps.0.block1.1.weight', 'backbone.mlps.0.block1.1.bias', 'backbone.mlps.0.block2.0.alpha', 'backbone.mlps.0.block2.0.beta', 'backbone.mlps.0.block2.1.weight', 'backbone.mlps.0.block2.1.bias', 'backbone.mlps.1.block1.0.alpha', 'backbone.mlps.1.block1.0.beta', 'backbone.mlps.1.block1.1.weight', 'backbone.mlps.1.block1.1.bias', 'backbone.mlps.1.block2.0.alpha', 'backbone.mlps.1.block2.0.beta', 'backbone.mlps.1.block2.1.weight', 'backbone.mlps.1.block2.1.bias', 'backbone.mlps.2.block1.0.alpha', 'backbone.mlps.2.block1.0.beta', 'backbone.mlps.2.block1.1.weight', 'backbone.mlps.2.block1.1.bias', 'backbone.mlps.2.block2.0.alpha', 'backbone.mlps.2.block2.0.beta', 'backbone.mlps.2.block2.1.weight', 'backbone.mlps.2.block2.1.bias', 'backbone.mlps.3.block1.0.alpha', 'backbone.mlps.3.block1.0.beta', 'backbone.mlps.3.block1.1.weight', 'backbone.mlps.3.block1.1.bias', 'backbone.mlps.3.block2.0.alpha', 'backbone.mlps.3.block2.0.beta', 'backbone.mlps.3.block2.1.weight', 'backbone.mlps.3.block2.1.bias', 'backbone.sequence_pos_encoder.pe', 'backbone.embed_timestep.sequence_pos_encoder.pe', 'backbone.embed_timestep.time_embed.0.weight', 'backbone.embed_timestep.time_embed.0.bias', 'backbone.embed_timestep.time_embed.2.weight', 'backbone.embed_timestep.time_embed.2.bias', 'input_mapping.weight', 'input_mapping.bias', 'sequence_pos_encoder.pe', 'speaker_embedding.weight', 'speaker_mu.weight', 'speaker_mu.bias', 'speaker_logvar.weight', 'speaker_logvar.bias', 'audio_encoder.feat_extractor.0.weight', 'audio_encoder.feat_extractor.0.bias', 'audio_encoder.feat_extractor.3.weight', 'audio_encoder.feat_extractor.3.bias', 'audio_encoder.feat_extractor.6.weight', 'audio_encoder.feat_extractor.6.bias', 'audio_encoder.feat_extractor.9.weight', 'audio_encoder.feat_extractor.9.bias', 'output_process.poseFinal.weight', 'output_process.poseFinal.bias']
unexpected_keys ['state', 'param_groups']
Traceback (most recent call last):
  File "scripts/test_RAG_ted.py", line 170, in <module>
    load_model_wo_clip(model, state_dict)
  File "/home/zlq/project/LivelySpeaker-main/scripts/mdm_utils/model_util.py", line 9, in load_model_wo_clip
    assert len(unexpected_keys) == 0
AssertionError

**Comment by zyhbili** [comment]
"Loading checkpoints from [ckpts/TED/opt000586891.pt]... "  It seems that you load the optimizer instead of the model?
