### ISSUE TITLE
beat test issue

### ISSUE THREAD

**Issue by anomySz** [zyhbili/LivelySpeaker#14]
Hi, 
I faced with this issue.

2024-03-25 20:38:54.863 | INFO     | dataloaders.beat:__init__:106 - Audio bit rate: 16000
2024-03-25 20:38:54.863 | INFO     | dataloaders.beat:__init__:107 - Reading data './datasets/beat_cache/beat_4english_15_141/test/'...
2024-03-25 20:38:54.863 | INFO     | dataloaders.beat:__init__:109 - loading the dataset cache...
64
Loading checkpoints from [ckpts/BEAT/RAG.pt]...
missing_keys []
unexpected_keys ['backbone.mlps.4.block1.0.alpha', 'backbone.mlps.4.block1.0.beta', 'backbone.mlps.4.block1.1.weight', 'backbone.mlps.4.block1.1.bias', 'backbone.mlps.4.block2.0.alpha', 'backbone.mlps.4.block2.0.beta', 'backbone.mlps.4.block2.1.weight', 'backbone.mlps.4.block2.1.bias', 'backbone.mlps.5.block1.0.alpha', 'backbone.mlps.5.block1.0.beta', 'backbone.mlps.5.block1.1.weight', 'backbone.mlps.5.block1.1.bias', 'backbone.mlps.5.block2.0.alpha', 'backbone.mlps.5.block2.0.beta', 'backbone.mlps.5.block2.1.weight', 'backbone.mlps.5.block2.1.bias', 'backbone.mlps.6.block1.0.alpha', 'backbone.mlps.6.block1.0.beta', 'backbone.mlps.6.block1.1.weight', 'backbone.mlps.6.block1.1.bias', 'backbone.mlps.6.block2.0.alpha', 'backbone.mlps.6.block2.0.beta', 'backbone.mlps.6.block2.1.weight', 'backbone.mlps.6.block2.1.bias', 'backbone.mlps.7.block1.0.alpha', 'backbone.mlps.7.block1.0.beta', 'backbone.mlps.7.block1.1.weight', 'backbone.mlps.7.block1.1.bias', 'backbone.mlps.7.block2.0.alpha', 'backbone.mlps.7.block2.0.beta', 'backbone.mlps.7.block2.1.weight', 'backbone.mlps.7.block2.1.bias']

Do you know how to solve this issue?
Thank you.

**Comment by zyhbili** [comment]
It seems the network has 4 layers while there are 8 layers parameters in the checkpoints. 
I log the network config into the saved ckpt path before training start, and load it before evaluation. Please check the logged config file in the ckpt path.

**Comment by zyhbili** [comment]
Sorry, i provide the wrong args.json. You could change "layers": 4 to 8 instead.

**Comment by anomySz** [comment]
Thank you!
