### ISSUE TITLE
Dataset split for BEAT

### ISSUE THREAD

**Issue by sanjayss34** [zyhbili/LivelySpeaker#2]
Hi, can you please provide the dataset split (train / val / test) you used for BEAT?

**Comment by l-dawei** [comment]
+1

**Comment by zyhbili** [comment]
We follow the dataset split in origin [BEAT](https://github.com/PantoMatrix/BEAT/blob/main/dataloaders/preprocessing.ipynb) and use the speakers 2,4,6,8.

**Comment by GuangtaoLyu** [comment]
code on BEAT. when will you release the code?

**Comment by zyhbili** [comment]
> code on BEAT. when will you release the code?

Sorry for the delay in releasing the code. I'm now busy with the coming cvpr ddl and  I would reorganize the code and document after that.

**Comment by GuangtaoLyu** [comment]
> > code on BEAT. when will you release the code?
> 
> Sorry for the delay in releasing the code. I'm now busy with the coming cvpr ddl and I would reorganize the code and document after that.

来催更啦。
祝你cvpr有个满意的结果。
老哥能不能分享一下BEAT部分的代码？
谢谢
